### ISSUE TITLE
New VR-Banking app doesn't Start!

### ISSUE THREAD

**Issue by Leonm99** [Unbrick/VRXposed#4]
Hello dear developer, the new dirty version isn't working with the newest version of Vr-Banking. Will you fix this?

**Comment by Unbrick** [comment]
I'm trying to. Sadly they improved the connection between the VR-Banking application and the anti-xposed framwork. The app is now requesting essential data (UDIs, Strings, etc...) from the anti-xposed framework which aren't passed when xposed was found. This usually leads to a crash of the app. Due to this it's now very hard to break. 

I'll try to get some native code of the anti-xposed framwork hooked, until then the only workaround is using an old VR-Banking app version. I'll give my best!

**Comment by Leonm99** [comment]
Okey, I really appreciate your quick response!

Is it really possible to use an older version of Vr-Banking or will I get forced to update the app?

Thank you for your hard work anyway!

**Comment by Unbrick** [comment]
You can disable auto-updates in google play store, but i dont know if the old version is still supported by the server. Just give it a shot!

**Comment by Leonm99** [comment]
Okey I'll try to find an older version of VR-Banking

**Comment by MBRKiNG** [comment]
I have found an oder Version in my titanium backup  BBBank app v16.15.06 works without any problems. ATM there are no checks oder Version woks fine.

**Comment by mist** [comment]
I'm using BBBank 16.20.02 without problems - I can upload it somewhere but I wouldn't trust anybodys binaries with banking apps...

**Comment by X4** [comment]
How about RootCloak? Doesn't help, I tried, but don't know why.

**Comment by Unbrick** [comment]
RootCloack hides some parts of root, i'm not even sure if it tries to hide the Xposed framework. The pronom framework checks for way more than RootCloack could hide (running processes, some boleans which are true when xposed framework is installed, files on the local system, other apps which are commonly used with xposed etc...). I coudn't event figure out what pronom is checking for because all checks are done in native C which is very difficult to reverse. 

I'm not sure if i'm able to crack the latest version, the only real solution/workaround would be using an older version. I'm very sorry about that. 

I'll let you know when i make any progress!

**Comment by lonesomewalker** [comment]
Still an issue :-)

Actually contacted my credit institute, asking why they block xposed.

Answer was: this framework makes your smartphone insecure, says their internal developers also their external app hardening company...

**Comment by danielehrhardt** [comment]
Something new here?

**Comment by danielehrhardt** [comment]
I got it working:
1. run as Root in a Terminal: `su -c chmod 000 /proc/net/unix `
2. Open Magisk Hide and add the App to the Hide List
3. Open Magisk go to Settings and click on Magisk Manager hide
4. Clear the Storage of the VR Secure Go App and start it.
